### ISSUE TITLE
Project Support

### ISSUE THREAD

**Issue by padriba** [Bio-Linux/build-bio-linux#3]
Is this project still supported? because when I click on the link [http://environmentalomics.org/bio-linux](http://environmentalomics.org/bio-linux) I got Account Suspended

**Comment by tony-travis** [comment]
On 04/07/2023 11:33, padriba wrote:
> Is this project still supported? because when I click on the link 
> http://environmentalomics.org/bio-linux 
> <http://environmentalomics.org/bio-linux> I got Account Suspended

Hi, Padriba.

I'm last man standing on the Bio-Linux project, which is now part of 
Debian-Med:

> https://www.debian.org/devel/debian-med/

Instead of installing Bio-Linux, I recommend:

Install Ubuntu-MATE 22.04 LTS from USB:

> https://ubuntu-mate.org/download/amd64/jammy/

Then boot the system, login on the desktop and in a terminal window:

sudo -i
apt update
apt install med-bio

This will install many of the packages that were present in Bio-Linux.

If you want to know what happened to the NERC Bio-Linux project, please 
contact Tracey Timms-Wilson (in CC).

HTH,

   Tony.

-- 
Minke Informatics Limited, Registered in Scotland - Company No. SC419028
Registered Office: 3 Donview, Bridge of Alford, AB33 8QJ, Scotland (UK)
tel. +44(0)19755 63548                    http://minke-informatics.co.uk
mob. +44(0)7985 078324        ***@***.***

**Comment by padriba** [comment]
I will contact you as soon as I install the med-bio package.
